name: Automated API Tests with Postman CLI

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 15 * * *' # Runs daily at 3:00 PM GMT
  workflow_dispatch: # Allows manual triggering

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
        continue-on-error: false

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}

      - name: Install Newman and reporters
        run: |
          npm install -g newman
          npm install -g newman-reporter-html
          npm install -g newman-reporter-allure
        continue-on-error: false

      - name: Run API tests with Newman
        run: |
          newman run "https://api.getpostman.com/collections/19630110-9d75580f-6dc3-454b-b47b-7ef20e57d3d6?apikey=${{ secrets.POSTMAN_API_KEY }}" \
            -r html,allure,cli \
            --reporter-html-export newman-report.html \
            --reporter-allure-export allure-results
        continue-on-error: false

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: newman-report.html
          retention-days: 7

      - name: Upload Allure results (raw)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
          retention-days: 7

      - name: Generate Allure report
        if: always()
        run: |
          npx allure generate allure-results -o allure-report --clean
        continue-on-error: false

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 7
